"""empty message

Revision ID: 30d7743419ba
Revises: 560aed489e6f
Create Date: 2018-05-07 16:44:58.938432

"""

# revision identifiers, used by Alembic.
revision = '30d7743419ba'
down_revision = '560aed489e6f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=True),
    sa.Column('year', sa.String(length=10), nullable=True),
    sa.Column('month', sa.String(length=10), nullable=True),
    sa.Column('image', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('awards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=True),
    sa.Column('year', sa.String(length=10), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('images', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('awards')
    op.drop_table('pics')
    ### end Alembic commands ###
