"""empty message

Revision ID: 40e7673cbeca
Revises: 4a0afbf6ad07
Create Date: 2016-11-05 15:46:39.652674

"""

# revision identifiers, used by Alembic.
revision = '40e7673cbeca'
down_revision = '4a0afbf6ad07'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('images', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'images')
    ### end Alembic commands ###
