"""empty message

Revision ID: 4a0afbf6ad07
Revises: None
Create Date: 2016-10-31 21:27:46.498092

"""

# revision identifiers, used by Alembic.
revision = '4a0afbf6ad07'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('details', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'details')
    ### end Alembic commands ###
