"""empty message

Revision ID: 560aed489e6f
Revises: 40e7673cbeca
Create Date: 2017-04-19 12:24:17.576143

"""

# revision identifiers, used by Alembic.
revision = '560aed489e6f'
down_revision = '40e7673cbeca'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publication', sa.Column('attach', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publication', 'attach')
    ### end Alembic commands ###
